<a href="https://colab.research.google.com/github/DeepsphereAI/AIWorkshop/blob/master/SEM-2/Data%20Science/Programs/LAB_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Array shape
print(a.shape)
print(b.shape)

# Array data type
print(a.dtype)


(5,)
(2, 3)
int64


In [ ]:
# Array arithmetic operations
c = a + 2
print(c)

d = a * 2
print(d)


[3 4 5 6 7]
[ 2  4  6  8 10]


In [ ]:
# Array aggregations
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())


15
3.0
5
1
